include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    unawaited_futures: true
    strict_casts: true
    no_implicit_dynamic: true
    require_trailing_commas: true
    avoid_print: false


